{
  "name": "catch-express-error",
  "version": "1.0.2",
  "description": "It is a Node.js package for handling and catching errors in Express.js applications.",
  "main": "source/cjs/index.cjs",
  "module": "source/esm/index.mjs",
  "author": "nextyfine-dev",
  "license": "MIT",
  "exports": {
    ".": {
      "require": "./source/cjs/index.cjs",
      "import": "./source/esm/index.mjs"
    }
  },
  "types": "./source/index.d.ts",
  "scripts": {
    "build": "yarn run build:cjs && yarn run build:esm",
    "build:cjs": "npx tsc -p tsconfig.cjs.json && mv source/cjs/index.js source/cjs/index.cjs",
    "build:esm": "npx tsc -p tsconfig.json && mv source/esm/index.js source/esm/index.mjs"
  },
  "devDependencies": {
    "@types/express": "^4.17.17",
    "@types/node": "^20.4.2",
    "express": "^4.18.2",
    "tslib": "^2.6.0",
    "typescript": "^5.1.6",
    "winston": "^3.10.0"
  },
  "files": [
    "source"
  ],
  "keywords": [
    "error handler",
    "error handling middleware",
    "express",
    "middleware",
    "validation",
    "error handling",
    "async",
    "typescript",
    "request",
    "response",
    "utility",
    "utilities",
    "validation middleware",
    "express middleware",
    "async error handling",
    "request validation",
    "response handling",
    "error management",
    "error wrapper",
    "catch errors",
    "express errors",
    "request errors",
    "response errors",
    "request validation middleware",
    "response error handling",
    "express error handler"
  ],
  "repository": {
    "type": "git",
    "url": "git+https://github.com/nextyfine-dev/catch-express-errors.git"
  },
  "bugs": {
    "url": "https://github.com/nextyfine-dev/catch-express-errors/issues"
  },
  "homepage": "https://github.com/nextyfine-dev/catch-express-errors#readme"
}